tech_uni/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login',
    ),
    url(
        regex=r'^login-dispatch/$',
        view=views.LoginDispatcher.as_view(),
        name='login_dispatch',
    ),
    url(
        regex=r'^password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password_change',
    ),

]

tech_uni/teachers/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^dashboard/$',
        view=views.TeacherDashboard.as_view(),
        name='dashboard',
    ),
    url(
        regex=r'^edit-profile/$',
        view=views.TeacherEditProfileView.as_view(),
        name='edit_profile',
    ),
    url(
        regex=r'publication/$',
        view=views.TeacherPublicationListView.as_view(),
        name='publication_list',
    ),
    url(
        regex=r'departments/info/edit/$',
        view=views.DepartmentInfoUpdateView.as_view(),
        name='edit_department_info',
    ),
    url(
        regex=r'departments/structure/edit/$',
        view=views.DepartmentStructUpdateView.as_view(),
        name='edit_department_struct',
    ),
    url(
        regex=r'publication/create/$',
        view=views.TeacherPublicationCreateView.as_view(),
        name='publication_create',
    ),
    url(
        regex=r'laboratory/list/$',
        view=views.LaboratoryUpdateListView.as_view(),
        name='laboratory_list',
    ),
    url(
        regex=r'school-subject/list/$',
        view=views.SchoolSubjectListView.as_view(),
        name='school_subject_list',
    ),
    url(
        regex=r'school-subject/(?P<pk>\d+)/edit/$',
        view=views.SchoolSubjectEditView.as_view(),
        name='school_subject_edit',
    ),
    url(
        regex=r'(?P<slug>[\w-]+)/structure/$',
        view=views.DepartmentTeacherStructureView.as_view(),
        name='department_structure',
    ),
    url(
        regex=r'publication/(?P<pk>\d+)/edit/$',
        view=views.TeacherPublicationUpdateView.as_view(),
        name='publication_edit',
    ),
    url(
        regex=r'laboratory/(?P<pk>\d+)/edit/$',
        view=views.LaboratoryEditView.as_view(),
        name='laboratory_edit',
    ),
    url(
        regex=r'publication/(?P<pk>\d+)/delete/$',
        view=views.TeacherPublicationDeleteView.as_view(),
        name='publication_delete',
    ),
    url(
        regex=r'laboratory/(?P<pk>\d+)/delete/$',
        view=views.LaboratoryDeleteView.as_view(),
        name='laboratory_delete',
    ),
    url(
        regex=r'(?P<slug>[\w-]+)/(?P<teacher>[\w-]+)/$',
        view=views.TeacherDetailView.as_view(),
        name='detail',
    ),
]

tech_uni/tech_uni/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('^', include('accounts.urls',
                     namespace='accounts')),

    url('^departments/', include('departments.urls',
                                 namespace='departments')),

    url('^auth/', include('django.contrib.auth.urls')),

    url(r'^teachers/', include('teachers.urls',
                               namespace='teachers'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_uni/teachers/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.http import Http404
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from departments.models import Department
from profiles.mixins import AbsUserProfile


class TeacherQuerySet(models.QuerySet):
    def habilitated(self):
        return self.filter(
            academic_title__in=self.model.HABILITATED_ACADEMIC_TITLES)

    def non_habilitated(self):
        return self.exclude(
            academic_title__in=self.model.HABILITATED_ACADEMIC_TITLES)


class Teacher(AbsUserProfile):
    class Meta:
        verbose_name = _('teacher profile')
        verbose_name_plural = _('teacher profiles')

    ASSISTANT = 1
    CHIEF_ASSISTANT = 2
    TEACHER = 3
    SENIOR_TEACHER = 4
    DOCENT = 5
    PROFESSOR = 6

    ACADEMIC_CHOICES = (
        (ASSISTANT, _('Assistant')),
        (CHIEF_ASSISTANT, _('Chief Assistant')),
        (TEACHER, _('Teacher')),
        (SENIOR_TEACHER, _('Senior Teacher')),
        (DOCENT, _('Docent')),
        (PROFESSOR, _('Professor'))
    )

    HABILITATED_ACADEMIC_TITLES = (DOCENT, PROFESSOR,)

    academic_title = models.PositiveSmallIntegerField(_('title'),
                                                      choices=ACADEMIC_CHOICES,
                                                      default=1)
    degree = models.CharField(_('Degree'), max_length=128)

    objects = TeacherQuerySet.as_manager()

    def is_habilitated(self):
        return self.academic_title in self.HABILITATED_ACADEMIC_TITLES

    def get_department(self):
        try:
            return self.department.department
        except models.ObjectDoesNotExist:
            return None

    def get_absolute_url(self):
        try:
            return reverse('teachers:detail',
                           kwargs={'slug': self.get_department().slug,
                                   'teacher': self.slug})
        except AttributeError:
            raise Http404

    def get_dashboard_url(self):
        return reverse('teachers:dashboard')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class TeacherDepartment(models.Model):
    class Meta:
        verbose_name = _('Teacher Department')
        verbose_name_plural = _('Teachers Department')

    teacher = models.OneToOneField(Teacher, related_name='department')
    department = models.ForeignKey(Department,
                                   related_name='teacher_department')

    def __str__(self):
        return '{}: {}'.format(self.department, self.teacher)


class TeacherDepartmentLeader(models.Model):
    class Meta:
        verbose_name = _('Teacher Department Leader')
        verbose_name_plural = _('Teacher Departments Leaders')

    teacher = models.OneToOneField(Teacher,
                                   related_name='teacher_department_leader')
    department = models.OneToOneField(Department,
                                      related_name='teacher_leader')

    def save(self, **kwargs):
        self.full_clean()
        super(TeacherDepartmentLeader, self).save(**kwargs)

    def clean(self):
        if self.teacher.get_department() != self.department:
            raise ValidationError(
                _('Teacher can not be from different department.'))

    def __str__(self):
        return '{}: {}'.format(self.department, self.teacher)


class SchoolSubject(models.Model):
    class Meta:
        verbose_name = _('School Subject')
        verbose_name_plural = _('School Subjects')

    department = models.ForeignKey(Department,
                                   related_name='school_subject_set')
    teachers = models.ManyToManyField(Teacher,
                                      related_name='school_subject_set')
    title = models.CharField(_('title'), max_length=256)
    description = models.TextField(_('description'))

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Publication(models.Model):
    class Meta:
        verbose_name = _('Publication')
        verbose_name_plural = _('Publications')

    teacher = models.ForeignKey(Teacher)
    title = models.CharField(_('Title'), max_length=512)
    journal = models.CharField(_('Journal'), max_length=512)
    authors = models.CharField(_('Author'), max_length=512)
    release_date = models.DateField(_('Release Date'))

    def __str__(self):
        return '{}: {}...'.format(self.teacher.get_full_name(),
                                  self.title[:25])

tech_uni/teachers/forms.py
from django import forms

from teachers.models import Teacher, Publication


class TeacherModelForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = (
            'first_name', 'second_name', 'last_name',
            'email', 'phone_number', 'description',
        )


class BasePublicationModelForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = ('title', 'journal', 'authors', 'release_date')


class PublicationCreateModelForm(BasePublicationModelForm):
    def save(self, commit=True):
        instance = super(PublicationCreateModelForm, self).save(commit=False)
        instance.teacher = self.data.get('profile')
        if commit:
            instance.save()
        return instance

tech_uni/templates/teachers/_navbar.html
{% load i18n %}
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{{ department.get_absolute_url }}">
                        <i class="material-icons">home</i>
                        <p class="hidden-lg hidden-md">{% trans 'Home' %}</p>
                    </a>
                </li>
                <li>
                </li>
                {% comment %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="material-icons">notifications</i>
                            <span class="notification">5</span>
                            <p class="hidden-lg hidden-md">Notifications</p>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Mike John responded to your email</a></li>
                            <li><a href="#">You have 5 new tasks</a></li>
                            <li><a href="#">You're now friend with Andrew</a></li>
                            <li><a href="#">Another Notification</a></li>
                            <li><a href="#">Another One</a></li>
                        </ul>
                    </li>
                    {% endcomment %}
                <li>
                    <a href="{{ object.get_absolute_url }}">
                        <i class="material-icons">person</i>
                        <p class="hidden-lg hidden-md">Profile</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">
                        <i class="material-icons">exit_to_app</i>
                        <p class="hidden-lg hidden-md">{% trans 'Logout' %}</p>
                    </a>
                </li>
            </ul>
            {% comment %}
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group  is-empty">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="material-input"></span>
                    </div>
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </form>
                {% endcomment %}
        </div>
    </div>
</nav>

tech_uni/templates/teachers/base_laboratory_form.html
{% extends view.base %}
{% load i18n widget_tweaks %}

{% block content %}
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <h4 class="title">{% trans 'Edit Publication' %}</h4>
            </div>
            <div class="card-content">
                <form action="" method="post">{% csrf_token %}
                    <input type="hidden" name="teacher" value="{{ request.user.get_profile.pk }}">
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.room_number.label }} *</label>
                            {{ form.room_number|attr:'class:form-control' }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.name.label }} *</label>
                            {{ form.name|attr:'class:form-control' }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.content.label }} *</label>
                            {{ form.content|attr:'class:form-control' }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info pull-right">{% trans 'Update' %}</button>
                    {{ form.image}}

                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

tech_uni/templates/teachers/base_teacher.html
{% extends '__base_profile.html' %}
{% load static i18n %}

{% block navigation_bar %}
    {% include 'teachers/_navbar.html' %}
{% endblock navigation_bar %}

{% block sidebar %}
    <div class="sidebar" data-color="blue" data-image="{% static "img/sidebar-1.jpg" %}">
        <!--
            Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

            Tip 2: you can also add an image using data-image tag
        -->
        <div class="logo">
            <a href="http://www.tu-sliven.com/" class="simple-text">
                {% trans "EPF Sliven" %}
            </a>
        </div>

        <div class="sidebar-wrapper">
            <ul class="nav">
                {% include 'teachers/dashboard_elements/_elements.html' %}
                {% block sidebar_list %}{% endblock sidebar_list %}
            </ul>
        </div>
    </div>
{% endblock sidebar %}

tech_uni/templates/teachers/department_info_edit.html
{% extends view.base %}
{% load i18n %}

{% block content %}

    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <h4 class="title">{% trans 'Edit Department Info' %}</h4>
            </div>
            <div class="card-content">
                <form action="" method="post">{% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>{{ form.content.label }} *</label>
                                <div class="form-group label-floating">
                                    <label class="control-label"></label>
                                    <textarea name="{{ form.content.name }}" class="form-control"
                                              rows="5">{{ form.content.value }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info pull-right">{% trans 'Update' %}</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

tech_uni/templates/teachers/department_structure.html
{% extends 'departments/base_structure.html' %}
{% load i18n %}

{% block participants %}
    <div class="">
        <div class="profile-tabs">
            <div class="nav-align-center">
                <ul class="nav nav-pills nav-pills-info" role="tablist">
                    <li>
                        <a href="#habilitated" role="tab" data-toggle="tab">
                            <i class="material-icons">group</i>
                            {% trans 'Habilitated' %}
                        </a>
                    </li>
                    <li class="active">
                        <a href="#leader" role="tab" data-toggle="tab">
                            <i class="material-icons">person</i>
                            {% trans 'Leader' %}
                        </a>
                    </li>
                    <li>
                        <a href="#nonhabilitated" role="tab" data-toggle="tab">
                            <i class="material-icons">group</i>
                            {% trans 'Non-habilitated' %}
                        </a>
                    </li>
                </ul>

                <div class="tab-content gallery">
                    <div class="tab-pane" id="habilitated">
                        <div class="row">
                            {% for teacher in habilitated %}
                                {% include 'teachers/generics/_teacher_rotating_card.html' with object=teacher %}
                            {% empty %}
                                <h4>{% trans 'There are no teachers added in that group until now.' %}</h4>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="tab-pane text-center active" id="leader">
                        <div class="row">
                            {% include 'teachers/generics/_teacher_rotating_card.html' with object=leader %}
                        </div>
                    </div>
                    <div class="tab-pane" id="nonhabilitated">
                        <div class="row">
                            {% for teacher in non_habilitated %}
                                {% include 'teachers/generics/_teacher_rotating_card.html' with object=teacher %}
                            {% empty %}
                                <h4>{% trans 'There are no teachers added in that group until now.' %}</h4>
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- End Tabs -->
    </div>
{% endblock participants %}

tech_uni/templates/teachers/laboratory_create.html
{% extends 'teachers/base_laboratory_form.html' %}

tech_uni/templates/teachers/laboratory_edit.html
{% extends 'teachers/base_laboratory_form.html' %}

tech_uni/templates/teachers/normal_teacher.html
{% extends 'teachers/base_teacher.html' %}

tech_uni/templates/teachers/profile_detail.html
{% extends '__base_particles.html' %}
{% load static i18n %}

{% block navigation %}
    {% include 'departments/_teacher_navigation.html' with object=department %}
{% endblock navigation %}

{% block content %}
    <div class="profile-page">
        <div class="wrapper">
            <div class="header">
                <div id="particles-js"></div>
            </div>

            <div class="main main-raised">
                <div class="profile-content">
                    <div class="container">
                        <div class="row">
                            <div class="profile">
                                <div class="avatar">
                                    <img src="{{ object.image.url }}" alt="Circle Image"
                                         class="img-circle img-responsive img-raised">
                                </div>
                                <div class="name">
                                    <h3 class="title">{{ object.get_full_name }}</h3>
                                    <h5>{{ object.get_academic_title_display }} {{ object.degree }}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="description text-center">
                            <p>{{ object.description }}</p>
                        </div>


                        <div class="row">
                            <div class="col-md-6 col-md-offset-3">
                                <div class="profile-tabs">
                                    <div class="nav-align-center">

                                        <ul class="nav nav-pills nav-pills-info" role="tablist">
                                            <li class="active">
                                                <a href="#studio" role="tab" data-toggle="tab">
                                                    <i class="material-icons">school</i>
                                                    {% trans 'Subjects' %}
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#work" role="tab" data-toggle="tab">
                                                    <i class="material-icons">book</i>
                                                    {% trans 'Publications' %}
                                                </a>
                                            </li>
                                        </ul>

                                        <div class="tab-content">

                                            <div class="tab-pane active" id="studio">
                                                {% for subject in subjects %}
                                                    <div class="row">
                                                        <a class="dropdown-header" role="button" data-toggle="collapse"
                                                           href="#collapseExample-{{ subject.id }}"
                                                           aria-expanded="false"
                                                           aria-controls="collapseExample-{{ subject.id }}">
                                                            <h4>{{ subject.title }}</h4>
                                                        </a>

                                                        <div class="collapse" id="collapseExample-{{ subject.id }}">
                                                            <div class="">{{ subject.description }}</div>
                                                        </div>
                                                    </div>
                                                    <hr>
                                                {% empty %}
                                                    <h4>{% trans 'There were no added school subjects led by' %} {{ object.get_full_name }}</h4>
                                                {% endfor %}
                                            </div>

                                            <div class="tab-pane text-center" id="work">
                                                {% for publication in publication_list %}
                                                    <div class="row">
                                                        <p><strong>{% trans 'Auhtor\s' %}: </strong>{{ publication.authors }}</p>
                                                        <p><strong>{% trans 'Magazine' %}: </strong>{{ publication.journal }}</p>
                                                        <p><strong>{% trans 'Title' %}: </strong>{{ publication.title }}</p>
                                                        <p>
                                                            <strong>{% trans 'Release Date' %}: </strong>{{ publication.release_date }}
                                                        </p>
                                                    </div>
                                                    <hr>
                                                {% empty %}
                                                    <h4> {% trans 'There are no added publications from theteacher untill now.' %} </h4>
                                                {% endfor %}
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <!-- End Profile Tabs -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

tech_uni/templates/teachers/publication_create.html
{% extends view.base %}
{% load i18n widget_tweaks static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
{% endblock css %}

{% block content %}
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <h4 class="title">{% trans 'Edit Publication' %}</h4>
            </div>
            {{ form.errors }}
            <div class="card-content">
                <form action="" method="post">{% csrf_token %}
                    {{ form.teacher }}
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.title.label }} *</label>
                            {{ form.title|attr:'class:form-control' }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.journal.label }} *</label>
                            {{ form.journal|attr:'class:form-control' }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.authors.label }} *</label>
                            {{ form.authors|attr:'class:form-control' }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group label">
                                <label class="control-label">{{ form.release_date.label }} *</label>
                                <input name="release_date" class="datepicker form-control" type="text"/>
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-info pull-right">{% trans 'Create' %}</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascript %}
    <script src="{% static "js/bootstrap-datepicker.js" %}"></script>

    <script type="text/javascript">
        $('.datepicker').datepicker({
            format:'yyyy-mm-dd',
            weekStart: 1,
            color: 'red'
        });
    </script>
{% endblock javascript %}

tech_uni/templates/teachers/publication_edit.html
{% extends view.base %}
{% load i18n widget_tweaks %}

{% block content %}
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <h4 class="title">{% trans 'Edit Publication' %}</h4>
            </div>
            <div class="card-content">
                <form action="" method="post">{% csrf_token %}
                    <input type="hidden" name="teacher" value="{{ request.user.get_profile.pk }}">
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.title.label }} *</label>
                            {{ form.title|attr:'class:form-control' }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.journal.label }} *</label>
                            {{ form.journal|attr:'class:form-control' }}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.authors.label }} *</label>
                            {{ form.authors|attr:'class:form-control' }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group label-floating">
                            <label class="control-label">{{ form.release_date.label }} *</label>
                            {{ form.release_date|attr:'class:form-control' }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info pull-right">{% trans 'Update' %}</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

tech_uni/templates/teachers/publication_list.html
{% extends view.base %}
{% load i18n %}

{% block content %}
    <div class="card card-nav-tabs">
        <div class="card-header" data-background-color="blue">
            <h5>{% trans 'Your publications' %}</h5>
        </div>

        <div class="card-content">
            {% if publication_list %}
                <div class="tab-content">
                    <div class="tab-pane active" id="profile">

                        <table class="table">
                            <tbody>
                            {% for publication in publication_list %}
                                <tr>
                                    <td>{{ publication.title }}</td>
                                    <td class="td-actions text-right">
                                        <a href="{% url 'teachers:publication_edit' publication.pk %}" rel="tooltip"
                                           title="{% trans "Edit Task" %}"
                                           class="btn btn-success btn-simple btn-xs">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <form action="{% url 'teachers:publication_delete' publication.pk %}"
                                              method="post">{% csrf_token %}
                                            <button type="submit" rel="tooltip" title="{% trans "Remove" %}"
                                                    class="btn btn-danger btn-simple btn-xs">
                                                <i class="material-icons">close</i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                {% include 'teachers/generics/_paginator.html' %}

            {% else %}
                <h3 class="text-center">
                    <small>{% trans 'There no publications added until now.' %} <a
                            href="{% url 'teachers:publication_create' %}">{% trans 'Add new now.' %}</a></small>
                </h3>
            {% endif %}
        </div>
    </div>
{% endblock content %}