tech_uni/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login',
    ),
    url(
        regex=r'^login-dispatch/$',
        view=views.LoginDispatcher.as_view(),
        name='login_dispatch',
    ),
    url(
        regex=r'^password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password_change',
    ),

]

tech_uni/departments/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'(?P<slug>[\w-]+)/laboratories/$',
        view=views.DepartmentLaboratoryListView.as_view(),
        name='laboratories',
    ),
    url(
        regex=r'(?P<slug>[\w-]+)/$',
        view=views.DepartmentDetailView.as_view(),
        name='home',
    ),
]

tech_uni/tech_uni/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('^', include('accounts.urls',
                     namespace='accounts')),

    url('^departments/', include('departments.urls',
                                 namespace='departments')),

    url('^auth/', include('django.contrib.auth.urls')),

    url(r'^teachers/', include('teachers.urls',
                               namespace='teachers'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tech_uni/departments/models.py
import os

from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from departments.tools import get_slug


def cover_image_upload_location(instance, filename):
    app_name = instance._meta.app_label
    model_name = instance._meta.model_name
    return os.path.join(app_name, model_name, instance.slug, filename)


class Department(models.Model):
    class Meta:
        verbose_name = _('Department')
        verbose_name_plural = _('Departments')

    slug = models.SlugField(unique=True, null=False, blank=True, verbose_name=_('slug'))
    name = models.CharField(max_length=150, verbose_name=_('name'))
    content = models.TextField(verbose_name=_('content'))
    struct_info = models.TextField(verbose_name=_('structure info'))

    cover_image = models.ImageField(upload_to=cover_image_upload_location, verbose_name=_('cover image'))

    def get_absolute_url(self):
        return reverse('departments:home', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name


@receiver(pre_save, sender=Department)
def setup_slug_field(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = get_slug(instance.name)


def laboratory_image_upload_location(instance, filename):
    app_name = instance._meta.app_label
    model_name = instance._meta.model_name
    return os.path.join(app_name, model_name, instance.department.slug, filename)


class Laboratory(models.Model):
    class Meta:
        verbose_name = _('Laboratory')
        verbose_name_plural = _('Laboratories')

    department = models.ForeignKey(Department, verbose_name=_('departament'))
    room_number = models.CharField(_('room number'), max_length=4, )
    name = models.CharField(_('name'), max_length=225, )
    content = models.TextField(_('content'))
    image = models.ImageField(upload_to=laboratory_image_upload_location)

    @property
    def fullname(self):
        return '{}: {}'.format(self.room_number, self.name)

    def __str__(self):
        return self.name

tech_uni/departments/views.py
# Create your views here.
from django.views import View
from django.views.generic import DetailView
from django.views.generic.base import TemplateResponseMixin
from django.views.generic.detail import SingleObjectMixin

from departments.models import Department


class DepartmentDetailView(DetailView):
    model = Department
    context_object_name = 'department'
    template_name = 'departments/department_detail.html'


class DepartmentLaboratoryListView(DetailView):
    model = Department
    template_name = 'departments/laboratories_list.html'

    def get_context_data(self, **kwargs):
        context = super(DepartmentLaboratoryListView, self).get_context_data(**kwargs)
        context['laboratory_set'] = self.object.laboratory_set.all()
        return context

tech_uni/templates/departments/_left_post.html
{% load static i18n %}
<div class="card card-plain card-blog">
    <div class="row">
        <div class="col-md-5">
            <img class="img img-raised img-responsive" src="{{ object.image.url }}">
        </div>
        <div class="col-md-7 text-center">
            <h3 class="card-title"> {{ object.name }} </h3>
            <h4> {% trans 'Cabinet No.' %} {{ object.room_number }}</h4>
            <p class="card-description">
                {{ object.content }}
            </p>
        </div>
    </div>
</div>

tech_uni/templates/departments/_right_post.html
{% load static i18n %}
<div class="card card-plain card-blog">
    <div class="row">
        <div class="col-md-7 text-center">
            <h3 class="card-title">{{ object.name }}</h3>
            <h5>{% trans 'Cabinet No.' %} {{ object.room_number }}</h5>
            <p class="card-description text-center">
                {{ object.content }}
            </p>
        </div>
        <div class="col-md-5">
            <img class="img img-raised img-responsive" src="{{ object.image.url }}">
        </div>
    </div>
</div>

tech_uni/templates/departments/_teacher_navigation.html
{% load i18n %}
<nav class="navbar navbar-info navbar-transparent navbar-fixed-top navbar-color-on-scroll">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {# LOGO #}
            <a class="navbar-brand" href="http://www.tu-sliven.com/">{% trans 'TU-Sofia EPF-Sliven' %}</a>
        </div>

        <div class="collapse navbar-collapse" id="navigation-example">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'departments:home' slug=view.kwargs.slug %}" target="">
                        {% trans 'Home' %}{{ kwargs.slug }}
                    </a>
                </li>
                <li>
                    <a href="{% url 'teachers:department_structure' slug=view.kwargs.slug %}" target="">
                        {% trans 'Structure' %}
                    </a>
                </li>
                <li>
                    <a href="{% url 'departments:laboratories' slug=view.kwargs.slug %}" target="">
                        {% trans 'Laboratories' %}
                    </a>
                </li>
                {% if False %}
                    <li>
                        <a href="{{ object.get_history_url }}" target="">
                            {% trans 'News' %}
                        </a>
                    </li>
                    <li>
                        <a href="{{ object.get_history_url }}" target="">
                            {% trans 'History' %}
                        </a>
                    </li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">account_circle</i>

                        {% trans 'Profile' %}
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        {% if request.user.is_authenticated %}
                            <li>
                                <a href="{{ request.user.get_profile.get_dashboard_url }}">{% trans 'Profile settings' %}</a>
                            </li>

                            <li><a href="{% url 'logout' %}">{% trans 'Logout profile' %}</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">{% trans 'Login profile' %}</a></li>
                        {% endif %}

                    </ul>

                </li>
            </ul>
        </div>
    </div>
</nav>

tech_uni/templates/departments/base_structure.html
{% extends '__base_particles.html' %}
{% load staticfiles i18n %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/rotating-card.css' %}">
{% endblock css %}

{% block content %}
    <body class="profile-page">


    <div class="wrapper">

        <div class="header">
            <div id="particles-js"></div>
        </div>

        <div class="main main-raised">
            <div class="profile-content">
                <div class="container">
                    <div class="row">
                        <h1 class="text-center">{% trans 'Strucutre' %}</h1>
                    </div>
                    <div class="description text-center">
                        <p>{{ department.struct_info }}</p>
                    </div>

                    <div class="row">
                        {% block participants %}
                        {% endblock participants %}
                    </div>

                </div>
            </div>
        </div>

    </div>
    <footer class="footer">
        <div class="container">
        </div>
    </footer>
{% endblock content %}

{% block javascript %}
    <script>
        $().ready(function () {
            $('[rel="tooltip"]').tooltip();

        });

        function rotateCard(btn) {
            var $card = $(btn).closest('.card-container');
            console.log($card);
            if ($card.hasClass('hover')) {
                $card.removeClass('hover');
            } else {
                $card.addClass('hover');
            }
        }

    </script>
{% endblock javascript %}

tech_uni/templates/departments/base_teacher_department.html
{% extends '__base_particles.html' %}

{% block navigation %}
    {% include 'departments/_teacher_navigation.html' %}
{% endblock navigation %}

tech_uni/templates/departments/department_detail.html
{% extends '__base_particles.html' %}
{% block content %}

    <div class="landing-page">
        <div class="wrapper">
            <div class="header header-filter"
                 style="background-image: url('{{ object.cover_image.url }}');">
                <div class="container">

                </div>
            </div>

            <div class="main main-raised">
                <div class="container">
                    <div class="section text-center section-landing">
                        <div class="row">
                            <div class="col-md-8 col-md-offset-2">
                                <h2 class="title">{{ object.name }}</h2>
                                <h5 class="description">{{ object.content }}</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">

            </footer>

        </div>
    </div>
{% endblock content %}

tech_uni/templates/departments/laboratories_list.html
{% extends '__base_particles.html' %}
{% load static i18n %}

{% block content %}
    <div class="profile-page">
        <div class="wrapper">
            <div class="header">
                <div id="particles-js"></div>
            </div>

            <div class="main main-raised">
                <div class="profile-content">
                    <div class="container">


                        <div class="text-center section">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2">
                                    <h1 class="title">{% trans 'Laboratories' %}</h1>
                                </div>
                            </div>
                        </div>

                        <div class="container">
                            <div class="row">
                                <div class="col-md-10 col-md-offset-1">
                                    {% for laboratory in laboratory_set %}
                                        {% cycle 'departments/_left_post.html' 'departments/_right_post.html' as post silent %}

                                        {% include post with object=laboratory %}

                                        {% if not forloop.last %}
                                            <hr>
                                        {% endif %}
                                    {% empty %}
                                        <h3 class="title text-center">{% trans 'The department have no laboratories that have been added.' %}</h3>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

tech_uni/templates/departments/laboratory.html
{% extends '__base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/laboratory.css' %}">
{% endblock css %}

{% block content %}
    <div class="conteiner fluid">
        <div class="row">
            <div id="row1" class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <img id="top-img-1" src="{% static 'img/card-cover-default.jpeg' %}" class="row1" alt=""/>
                <img id="top-img-2" src="{% static 'img/card-cover-default.jpeg' %}" class="row1" alt=""/>
                <img id="top-img-3" src="{% static 'img/card-cover-default.jpeg' %}" class="row1" alt=""/>

            </div>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div id="content" class="jumbotron">
                    <p>
                        <h2 id="headline">Use the Power of
                    <p></p>
                    Artificial Design Intelligence
                    </h2>
                    Wix ADI learns about you and applies this knowledge to
                    create the perfect website for your needs. From billions
                    of combinations including layouts, images, text, contact
                    forms and more, Wix ADI selects the most stunning just
                    for you - creating a one-of-a-kind free website.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="page-header">
        <h1></h1>
    </div>

    <div class="conteiner fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div id="content" class="jumbotron">
                    <p>
                        <h2 id="headline">Use the Power of
                    <p></p>
                    Artificial Design Intelligence
                    </h2>
                    Wix ADI learns about you and applies this knowledge to
                    create the perfect website for your needs. From billions
                    of combinations including layouts, images, text, contact
                    forms and more, Wix ADI selects the most stunning just
                    for you - creating a one-of-a-kind free website.
                    </p>
                </div>
            </div>
            <div id="row2" class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <img id="top-img-1" src="{% static 'img/card-cover-default.jpeg' %}" class="row2" alt=""/>
                <img id="top-img-2" src="{% static 'img/card-cover-default.jpeg' %}" class="row2" alt=""/>
                <img id="top-img-3" src="{% static 'img/card-cover-default.jpeg' %}" class="row2" alt=""/>
            </div>
        </div>
    </div>
    <div class="page-header">
        <h1></h1>
    </div>
{% endblock content %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/laboratory.js' %}"></script>
{% endblock javascript %}